let mySprite = sprites.create(assets.image`基本款`, SpriteKind.Player)
let mySprite2 = sprites.create(assets.image`槌子`, SpriteKind.Player)
let mySprite3 = sprites.create(assets.image`芋頭`, SpriteKind.Player)
let mySprite4 = sprites.create(assets.image`殭屍`, SpriteKind.Player)
let mySprite5 = sprites.create(assets.image`小辣椒`, SpriteKind.Player)
mySprite2.setPosition(103, 38)
mySprite3.setPosition(46, 50)
mySprite4.setPosition(42, 66)
mySprite5.setPosition(69, 48)
